"""RedisStreamTransport — cross-service transport for drive-ms (and similar).

Used when the service that emits events has a separate database and cannot
query the WorkflowTrigger table. Writes a structured message to a Redis Stream;
main-api's consumer (event_catalog.consumer) reads it and enqueues the Celery
task on the other side.

Requires the publisher install extra (redis only — no Django models needed).

Settings
--------
    EVENT_CATALOG = {
        'TRANSPORT': 'event_catalog.transport.redis_stream.RedisStreamTransport',
        'REDIS_URL':  'redis://localhost:6379/0',   # shared Redis instance
        'STREAM_NAME': 'event_catalog:events',       # must match main-api consumer
    }
"""
from __future__ import annotations

import json

from .base import BaseTransport

_DEFAULT_STREAM = 'event_catalog:events'


class RedisStreamTransport(BaseTransport):
    """Deliver events by writing to a Redis Stream (XADD).

    The Redis client is created lazily on the first send() call so that
    importing this module at startup does not require a live Redis connection.
    """

    def __init__(self) -> None:
        self._client = None

    # ── Internal ───────────────────────────────────────────────────────────────

    def _get_client(self):
        if self._client is None:
            import redis
            from django.conf import settings

            cfg = getattr(settings, 'EVENT_CATALOG', {})
            url = cfg.get('REDIS_URL', 'redis://localhost:6379/0')
            self._client = redis.from_url(url, decode_responses=True)
        return self._client

    def _get_stream_name(self) -> str:
        from django.conf import settings

        cfg = getattr(settings, 'EVENT_CATALOG', {})
        return cfg.get('STREAM_NAME', _DEFAULT_STREAM)

    # ── BaseTransport ──────────────────────────────────────────────────────────

    def send(
        self,
        event_name: str,
        org_id: str,
        entity_id: str,
        entity_scope: str,
        context: dict,
    ) -> None:
        """Write the event to the Redis Stream.

        Redis Streams only accept string values, so `context` is JSON-encoded.
        main-api's consumer decodes it before passing to the Celery task.

        The stream ID is auto-generated by Redis (* = server-assigned timestamp
        ID), giving a total ordering of events per stream.
        """
        self._get_client().xadd(
            self._get_stream_name(),
            {
                'event_name': event_name,
                'org_id': org_id,
                'entity_id': entity_id,
                'entity_scope': entity_scope,
                'context': json.dumps(context),
            },
        )
